/* GAVHAH per-campaign network: Call Office, Command Center, Conference Room */
(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const yi=(a,b)=>(typeof language!=='undefined'&&language==='en'?b:a);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const esc=(v='')=>{const d=document.createElement('div');d.textContent=String(v);return d.innerHTML};
const now=()=>new Date().toISOString();
const campaignId=()=>typeof state!=='undefined'&&state?.campaign?.id?state.campaign.id:'preview-campaign';
const planName=()=>typeof state!=='undefined'&&state?.campaign?.plan?state.campaign.plan:'Personal Askan';
const enabled=()=>['Chesed Quick','Askan Pro','Gabbai Pro','Organization','Custom'].includes(planName());
const userId=()=>typeof afCurrentUser!=='undefined'&&afCurrentUser?.id?afCurrentUser.id:'preview-user';
const userName=()=>typeof afCurrentUser!=='undefined'&&afCurrentUser?(afCurrentUser.user_metadata?.display_name||afCurrentUser.email?.split('@')[0]||afCurrentUser.phone||'עסקן'):'ר׳ משה';
const money=v=>`$${Math.round(Number(v||0)).toLocaleString()}`;
const dateText=v=>{if(!v)return yi('קיין צייט','No time');const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(d)};
const isUuid=v=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v||'');
const toastN=(a,b)=>typeof toast==='function'&&toast(a,b);
let officeTab='available', commandTab='open', roomChannel='all', currentLead='', currentDispatch='', currentReply='';
let data={leads:[],dispatch:[],messages:[]},sync=false,channel=null,loadedKey='';
const key=()=>`gavhah-campaign-network:${userId()}:${campaignId()}`;

function seed(){
 return {leads:[
  {id:uid('lead'),name:'ר׳ יצחק מאסקאוויטש',phone:'845-555-0182',source:'עסקן Referral',target:5000,priority:'high',status:'available',claimed_by:'',claimed_name:'',call_count:0,last_outcome:'',donation_amount:0,next_callback_at:'',note:'האט געגעבן פאר א ענליכע צוועק פאריאר.',created_at:now(),updated_at:now()},
  {id:uid('lead'),name:'משפחת גרינבוים',phone:'718-555-0147',source:'אלטע נדבנים',target:2500,priority:'normal',status:'callback',claimed_by:'member-demo',claimed_name:'ר׳ יואל',call_count:1,last_outcome:'רופן היינט ביינאכט',donation_amount:0,next_callback_at:new Date(Date.now()+4*3600000).toISOString(),note:'קען זיין א שיינע נדבה.',created_at:now(),updated_at:now()},
  {id:uid('lead'),name:'Anonymous Donor',phone:'',source:'Existing relationship',target:1000,priority:'normal',status:'donated',claimed_by:'member-demo2',claimed_name:'ר׳ מנחם',call_count:2,last_outcome:'געגעבן',donation_amount:1800,next_callback_at:'',note:'שיקן הכרת הטוב.',created_at:now(),updated_at:now()}
 ],dispatch:[
  {id:uid('job'),title:'אויפיקן די נייע געדרוקטע ליטעראטור',details:'פון דרוקעריי אין בארא פארק ביז 6:00.',category:'pickup',priority:'urgent',status:'open',created_by:'owner-demo',created_name:'Campaign Office',claimed_by:'',claimed_name:'',due_at:new Date(Date.now()+6*3600000).toISOString(),created_at:now(),updated_at:now()},
  {id:uid('job'),title:'ווער קען דרייוון הרב צום מסיבה?',details:'פון קרית יואל קיין וויליאמסבורג און צוריק.',category:'ride',priority:'high',status:'claimed',created_by:'owner-demo',created_name:'Campaign Office',claimed_by:'member-demo',claimed_name:'ר׳ יואל',due_at:new Date(Date.now()+86400000).toISOString(),created_at:now(),updated_at:now()},
  {id:uid('job'),title:'רופן הרב און בעטן אויפצוטרעטן',details:'גרינבוים מוז יעצט ארויסשטעקן; ווער קען איבערנעמען?',category:'call',priority:'high',status:'open',created_by:'member-demo2',created_name:'ר׳ מנחם',claimed_by:'',claimed_name:'',due_at:new Date(Date.now()+3*3600000).toISOString(),created_at:now(),updated_at:now()}
 ],messages:[
  {id:uid('msg'),author_id:'owner-demo',author_name:'Campaign Office',channel:'updates',body:'ברוכים הבאים אינעם קאנפרענץ־ראום. ביטע לאזט אייך הערן כסדר — א Update, עצה, חיזוק אדער שאלה.',reply_to:'',created_at:now(),reactions:2,reacted_by:[]},
  {id:uid('msg'),author_id:'member-demo',author_name:'ר׳ יואל',channel:'chizuk',body:'מ׳האט היינט שוין גערופן 18 מענטשן. יעדע פעולה שפאלט עולמות — לאמיר גיין ווייטער!',reply_to:'',created_at:now(),reactions:4,reacted_by:[]}
 ]};
}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(key()));data=x&&Array.isArray(x.leads)?x:seed()}catch{data=seed()}saveLocal()}
function saveLocal(){localStorage.setItem(key(),JSON.stringify(data))}
async function loadCloud(){sync=false;if(typeof afClient==='undefined'||!afClient||!isUuid(campaignId()))return;try{
 const [a,b,c]=await Promise.all([
  afClient.from('campaign_call_leads').select('*').eq('campaign_id',campaignId()).is('deleted_at',null).order('updated_at',{ascending:false}),
  afClient.from('campaign_command_items').select('*').eq('campaign_id',campaignId()).is('deleted_at',null).order('created_at',{ascending:false}),
  afClient.from('campaign_room_messages').select('*').eq('campaign_id',campaignId()).is('deleted_at',null).order('created_at',{ascending:false})
 ]);
 if(a.error||b.error||c.error)return;sync=true;
 data.leads=(a.data||[]).map(x=>({id:x.id,name:x.display_name,phone:x.phone||'',source:x.source_label||'',target:x.target_amount||0,priority:x.priority,status:x.status,claimed_by:x.claimed_by||'',claimed_name:x.claimed_name||'',call_count:x.call_count||0,last_outcome:x.last_outcome||'',donation_amount:x.donation_amount||0,next_callback_at:x.next_callback_at||'',note:x.note||'',created_at:x.created_at,updated_at:x.updated_at}));
 data.dispatch=(b.data||[]).map(x=>({id:x.id,title:x.title,details:x.details||'',category:x.category,priority:x.priority,status:x.status,created_by:x.created_by,created_name:x.created_name||'',claimed_by:x.claimed_by||'',claimed_name:x.claimed_name||'',due_at:x.due_at||'',created_at:x.created_at,updated_at:x.updated_at}));
 data.messages=(c.data||[]).map(x=>({id:x.id,author_id:x.author_id,author_name:x.author_name||'',channel:x.channel,body:x.body,reply_to:x.reply_to||'',created_at:x.created_at,reactions:x.reaction_count||0,reacted_by:[]}));saveLocal();subscribe();
 }catch{}}
function subscribe(){if(!sync||channel||typeof afClient==='undefined')return;channel=afClient.channel(`campaign-network-${campaignId()}`).on('postgres_changes',{event:'*',schema:'public',table:'campaign_call_leads',filter:`campaign_id=eq.${campaignId()}`},reload).on('postgres_changes',{event:'*',schema:'public',table:'campaign_command_items',filter:`campaign_id=eq.${campaignId()}`},reload).on('postgres_changes',{event:'*',schema:'public',table:'campaign_room_messages',filter:`campaign_id=eq.${campaignId()}`},reload).subscribe()}
async function reload(){await loadCloud();renderAll()}
async function upsertLead(x){if(!sync)return;await afClient.from('campaign_call_leads').upsert({id:x.id,campaign_id:campaignId(),display_name:x.name,phone:x.phone||null,source_label:x.source||null,target_amount:Number(x.target||0),priority:x.priority,status:x.status,claimed_by:x.claimed_by||null,claimed_name:x.claimed_name||null,call_count:Number(x.call_count||0),last_outcome:x.last_outcome||null,donation_amount:Number(x.donation_amount||0),next_callback_at:x.next_callback_at||null,note:x.note||null,updated_at:now(),deleted_at:null},{onConflict:'id'})}
async function upsertDispatch(x){if(!sync)return;await afClient.from('campaign_command_items').upsert({id:x.id,campaign_id:campaignId(),title:x.title,details:x.details||null,category:x.category,priority:x.priority,status:x.status,created_by:x.created_by,created_name:x.created_name||null,claimed_by:x.claimed_by||null,claimed_name:x.claimed_name||null,due_at:x.due_at||null,updated_at:now(),deleted_at:null},{onConflict:'id'})}
async function insertMessage(x){if(!sync)return;await afClient.from('campaign_room_messages').insert({id:x.id,campaign_id:campaignId(),author_id:x.author_id,author_name:x.author_name,channel:x.channel,body:x.body,reply_to:x.reply_to||null,reaction_count:x.reactions||0,created_at:x.created_at})}

function inject(){if($('#campaignOffice'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='campaign-network.css?v=1';document.head.appendChild(link);
 const homeAnchor=$('#kesherHome')||$('#focusHomeCard')||$('#homeCurrent');if(homeAnchor)homeAnchor.insertAdjacentHTML('afterend',`<div class="network-home-grid"><button class="network-home-card office" data-page="campaignOffice"><div class="home-line"><div><h3>☎ קאמפיין Call Office</h3><p>א כלליות׳דיגע באזע פאר אלע אקטיווע עסקנים: Available Numbers, Calls, נדבות און Live Progress.</p></div><span>›</span></div><div class="home-badges"><span id="officeHomeOpen">0 Available</span><span id="officeHomeCalled">0 Called</span><span id="officeHomeRaised">$0</span></div></button><button class="network-home-card command" data-page="commandCenter"><div class="home-line"><div><h3>⌘ קאמענד צענטער</h3><p>לייג ארויס א בקשה; איינער נעמט עס אן; יעדער ווייסט ווער איז אחראי.</p></div><span>›</span></div><div class="home-badges"><span id="commandHomeOpen">0 Open</span><span id="commandHomeClaimed">0 Claimed</span></div></button><button class="network-home-card room" data-page="conferenceRoom"><div class="home-line"><div><h3>☕ קאנפרענץ ראום</h3><p>Updates, חיזוק, הדרכה, עצות און א ווארעמער Campaign Coffee Room.</p></div><span>›</span></div><div class="home-badges"><span id="roomHomeMessages">0 Messages</span><span>Active members only</span></div></button></div>`);
 const app=$('.app');app.insertAdjacentHTML('beforeend',pagesHtml());document.body.insertAdjacentHTML('beforeend',modalsHtml());bind();
}
function gate(type){return `<div class="network-gate"><h3>🔒 ${yi('דער אפטיילונג הייבט זיך אן ביי Chesed Quick','This section starts with Chesed Quick')}</h3><p>${yi('Personal Askan האלט אייערע פערזענליכע קשרים און פאוקעס. Chesed Quick עפנט פאר יעדן קאמפיין דעם Shared Call Office, Command Center און Conference Room.','Personal Askan keeps private contacts and focus. Chesed Quick unlocks a shared Call Office, Command Center and Conference Room for each campaign.')}</p><button class="btn" data-open-modal="plans">${yi('זען Chesed Quick','View Chesed Quick')}</button></div>`}
function pagesHtml(){return `<section id="campaignOffice" class="page"><button class="back" data-page="home">← צוריק</button><div class="network-hero office"><div class="eyebrow">Chesed Quick+ · Campaign Call Office</div><h2>איין קאמפיין, איין Live Call Base</h2><p>יעדער עסקן האלט זיין פריוואטן קשר־ספר; דער Campaign Office האלט נאר די Shared Campaign Records וואס אקטיווע עסקנים דארפן וויסן.</p><div class="network-mantra">זע ווער איז שוין גערופן, ווער האט געגעבן, וואס איז Available, און ווער האט גענומען אחריות — אן איבעררופן דעם זעלבן מענטש צוויי מאל.</div></div><div id="officeGate"></div><div id="officeBody"><div class="office-stats" id="officeStats"></div><div class="network-toolbar"><input id="officeSearch" type="search" placeholder="זוך נאמען, פאון אדער Outcome…"><button id="addLead" class="btn">＋ Available Number</button></div><div id="officeTabs" class="network-tabs"></div><div class="active-members-only">👥 נאר אקטיווע Campaign Roles קענען זען דעם Shared Office. פערזענליכע נאטיצן בלייבן אינעם אייגענעם קשר־ספר.</div><div class="shared-preview-note">Preview: דאטע ווערט יעצט געהיטן אויפן Device. נאכן Migration 010 ווערט עס Shared און Live דורך Supabase Realtime.</div><div id="officeList" class="office-board"></div><div id="officeScore" class="card"></div></div></section>
<section id="commandCenter" class="page"><button class="back" data-page="home">← צוריק</button><div class="network-hero command"><div class="eyebrow">Chesed Quick+ · Dispatch Board</div><h2>קאמענד צענטער</h2><p>פירער און עסקנים קענען ארויסלייגן א קלארע בקשה. יעדער זאך האט א קנעפל: אננעמען, צוריקגעבן, פארענדיקן אדער קענסלען לויט Permissions.</p><div class="network-mantra">קיין זאך זאל נישט פאלן צווישן די בענק. איין בקשה, איין אחראי, איין נעקסטער שריט.</div></div><div id="commandGate"></div><div id="commandBody"><div id="commandSummary" class="command-summary"></div><div class="network-toolbar"><input id="commandSearch" type="search" placeholder="זוך בקשה, מענטש אדער פלאץ…"><button id="addDispatch" class="btn">＋ נייע בקשה</button></div><div id="commandTabs" class="network-tabs"></div><div class="accept-rule">✓ אננעמען ארבעט נאר ווען קיינער האט עס נאכנישט גענומען. דער נעמער קען צוריקגעבן; Creator אדער Managers קענען קענסלען. Completion בלייבט אין History.</div><div id="dispatchList"></div></div></section>
<section id="conferenceRoom" class="page"><button class="back" data-page="home">← צוריק</button><div class="network-hero room"><div class="eyebrow">Chesed Quick+ · Campaign Community</div><h2>קאנפרענץ ראום — דער קאמפיין קאווע־שטיבל</h2><p>עסקנים, לאזט זיך הערן. Updates, חיזוק, שאלות, עצות און א פלאץ זיך אויסצוגעבן נאך דער ארבעט — מיט כבוד און אחריות.</p><div class="network-mantra">קיין חילוק צי איר האט א גרויסן Update אדער איין ווארט: א לעבעדיגע מאנשאפט בלייבט צוזאמען ווען מענטשן לאזן זיך הערן.</div></div><div id="roomGate"></div><div id="roomBody"><div class="room-prompt"><strong>עסקנים בעטן: טיילט מיט יעדע שטיק צייט אייער ווארט אינעם קאמפיין</strong><small>וואס איז געלונגען? וואס שטעקט? ווער דארף חיזוק? וועלכע עצה קען העלפן?</small></div><div id="roomTabs" class="network-tabs"></div><div class="room-composer"><div id="replyPreview"></div><textarea id="roomText" maxlength="3000" placeholder="שרייבט א Update, חיזוק, הדרכה, עצה אדער א קשיא…"></textarea><div class="room-compose-actions"><select id="roomComposeChannel"><option value="updates">Updates</option><option value="chizuk">חיזוק</option><option value="guidance">הדרכה</option><option value="ideas">עצות / Ideas</option><option value="coffee">קאווע שטיבל</option></select><button id="sendRoom" class="btn">שיקן</button></div></div><div class="active-members-only">🔐 דער Conference Room איז נאר פאר אקטיווע Campaign Members. פריוואטע קעיס־דעטאלן אדער סענסיטיווע אינפארמאציע זאל מען נישט אריינלייגן אין א כלליות׳דיגן Chat.</div><div id="roomMessages"></div></div></section>`}
function modalsHtml(){return `<div id="leadEditor" class="modal"><div class="modal-card"><div class="modal-head"><h2>Available Number</h2><button class="close" data-network-close>✕</button></div><div class="form-grid"><label>נאמען / Label<input id="leadName"></label><div class="two-col"><label>פאון<input id="leadPhone" type="tel"></label><label>Source<input id="leadSource" placeholder="Referral, old list…"></label></div><div class="two-col"><label>Target Ask<input id="leadTarget" type="number" min="0"></label><label>Priority<select id="leadPriority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label></div><label>Campaign Note<textarea id="leadNote"></textarea></label><button id="saveLead" class="btn block">לייגן צום Available Board</button></div></div></div><div id="leadOutcome" class="modal"><div class="modal-card"><div class="modal-head"><h2>Call Outcome</h2><button class="close" data-network-close>✕</button></div><div class="form-grid"><label>Outcome<select id="leadOutcomeStatus"><option value="contacted">גערעדט</option><option value="callback">צוריקרופן</option><option value="donated">געגעבן</option><option value="not_interested">נישט אינטערעסירט</option><option value="no_answer">נישט אויפגעהויבן</option></select></label><label>קורצע Shared Note<textarea id="leadOutcomeNote"></textarea></label><div class="two-col"><label>Donation Amount<input id="leadDonation" type="number" min="0"></label><label>Callback Time<input id="leadCallback" type="datetime-local"></label></div><button id="saveLeadOutcome" class="btn block">היטן Outcome</button></div></div></div><div id="dispatchEditor" class="modal"><div class="modal-card"><div class="modal-head"><h2>נייע Command Request</h2><button class="close" data-network-close>✕</button></div><div class="form-grid"><label>וואס דארף געטון ווערן?<input id="dispatchTitle"></label><label>פרטים<textarea id="dispatchDetails"></textarea></label><div class="dispatch-category-grid" id="dispatchCategories"></div><div class="two-col"><label>Priority<select id="dispatchPriority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Due Time<input id="dispatchDue" type="datetime-local"></label></div><button id="saveDispatch" class="btn block">ארויסלייגן אין קאמענד צענטער</button></div></div></div>`}

function officeStats(){const leads=data.leads,called=leads.filter(x=>x.call_count>0||['contacted','callback','donated','not_interested','no_answer'].includes(x.status)).length,donors=leads.filter(x=>Number(x.donation_amount)>0).length,raised=leads.reduce((s,x)=>s+Number(x.donation_amount||0),0);return{all:leads.length,available:leads.filter(x=>x.status==='available').length,called,donors,raised}}
function renderHome(){const s=officeStats();$('#officeHomeOpen').textContent=`${s.available} Available`;$('#officeHomeCalled').textContent=`${s.called} Called`;$('#officeHomeRaised').textContent=money(s.raised);$('#commandHomeOpen').textContent=`${data.dispatch.filter(x=>x.status==='open').length} Open`;$('#commandHomeClaimed').textContent=`${data.dispatch.filter(x=>x.status==='claimed').length} Claimed`;$('#roomHomeMessages').textContent=`${data.messages.length} Messages`}
function renderGates(){const on=enabled();$('#officeGate').innerHTML=on?'':gate('office');$('#commandGate').innerHTML=on?'':gate('command');$('#roomGate').innerHTML=on?'':gate('room');$('#officeBody').style.display=on?'block':'none';$('#commandBody').style.display=on?'block':'none';$('#roomBody').style.display=on?'block':'none'}
function renderOffice(){const s=officeStats();$('#officeStats').innerHTML=`<div class="office-stat"><span>${yi('Available','Available')}</span><strong>${s.available}</strong></div><div class="office-stat"><span>${yi('גערופן','Called')}</span><strong>${s.called}</strong></div><div class="office-stat"><span>${yi('נדבנים','Donors')}</span><strong>${s.donors}</strong></div><div class="office-stat"><span>${yi('אויפגעברענגט','Raised')}</span><strong>${money(s.raised)}</strong></div>`;const tabs=[['available','Available'],['mine','מיינע Calls'],['called','גערופן'],['donated','געגעבן'],['all','אלע']];$('#officeTabs').innerHTML=tabs.map(([x,l])=>`<button class="network-tab ${officeTab===x?'on':''}" data-office-tab="${x}">${l}</button>`).join('');const q=($('#officeSearch').value||'').toLowerCase();let list=data.leads.filter(x=>{if(officeTab==='available'&&x.status!=='available')return false;if(officeTab==='mine'&&x.claimed_by!==userId())return false;if(officeTab==='called'&&!(x.call_count>0))return false;if(officeTab==='donated'&&!(Number(x.donation_amount)>0))return false;return !q||[x.name,x.phone,x.source,x.note,x.last_outcome].join(' ').toLowerCase().includes(q)});$('#officeList').innerHTML=list.length?list.map(leadCard).join(''):`<div class="network-empty">${yi('נישטא קיין רעקארדס אין דעם Filter.','No records in this filter.')}</div>`;renderScore()}
function leadCard(x){const mine=x.claimed_by===userId(),available=x.status==='available';return `<article class="lead-card" data-lead-id="${x.id}"><div class="lead-top"><div><h3>${esc(x.name)}</h3><p>${esc([x.phone,x.source].filter(Boolean).join(' · ')||'No details')}</p></div><strong>${x.target?money(x.target):''}</strong></div><div class="lead-tags"><span class="${available?'open':x.status==='donated'?'done':'claimed'}">${esc(x.status)}</span><span class="${x.priority==='urgent'?'urgent':''}">${esc(x.priority)}</span>${x.claimed_name?`<span>${esc(x.claimed_name)}</span>`:''}</div>${x.note?`<div class="lead-next">${esc(x.note)}</div>`:''}${x.last_outcome?`<div class="lead-next"><strong>Last:</strong> ${esc(x.last_outcome)}${x.donation_amount?` · ${money(x.donation_amount)}`:''}${x.next_callback_at?` · ${dateText(x.next_callback_at)}`:''}</div>`:''}<div class="lead-actions">${available?'<button class="claim-btn claim-lead">אננעמען</button>':''}${mine||available?'<button class="release-btn save-personal-kesher">＋ מיין קשרים</button>':''}${mine?'<button class="complete-btn log-lead">Call Outcome</button><button class="release-btn release-lead">צוריקגעבן</button>':''}</div></article>`}
function renderScore(){const scores={};for(const x of data.leads){if(!x.claimed_name)continue;const k=x.claimed_name;scores[k]??={calls:0,amount:0};scores[k].calls+=Number(x.call_count||0);scores[k].amount+=Number(x.donation_amount||0)}const arr=Object.entries(scores).sort((a,b)=>b[1].amount-a[1].amount);$('#officeScore').innerHTML=`<h3>${yi('Live עסקן־פארשריט','Live member progress')}</h3>${arr.length?arr.map(([name,v],i)=>`<div class="score-row"><div class="score-rank">${i+1}</div><div><strong>${esc(name)}</strong><small>${v.calls} Calls</small></div><div class="score-amount">${money(v.amount)}</div></div>`).join(''):`<div class="network-empty">${yi('נאך נישטא קיין Shared Activity.','No shared activity yet.')}</div>`}`}
function renderCommand(){const tabs=[['open','Open'],['claimed','Claimed'],['mine','מיינע'],['completed','Completed'],['all','All']];$('#commandTabs').innerHTML=tabs.map(([x,l])=>`<button class="network-tab ${commandTab===x?'on':''}" data-command-tab="${x}">${l}</button>`).join('');const open=data.dispatch.filter(x=>x.status==='open').length,claimed=data.dispatch.filter(x=>x.status==='claimed').length,done=data.dispatch.filter(x=>x.status==='completed').length;$('#commandSummary').innerHTML=`<div><span>Open</span><strong>${open}</strong></div><div><span>Claimed</span><strong>${claimed}</strong></div><div><span>Done</span><strong>${done}</strong></div>`;const q=($('#commandSearch').value||'').toLowerCase();const list=data.dispatch.filter(x=>{if(commandTab==='open'&&x.status!=='open')return false;if(commandTab==='claimed'&&x.status!=='claimed')return false;if(commandTab==='mine'&&x.claimed_by!==userId()&&x.created_by!==userId())return false;if(commandTab==='completed'&&x.status!=='completed')return false;return !q||[x.title,x.details,x.created_name,x.claimed_name,x.category].join(' ').toLowerCase().includes(q)});$('#dispatchList').innerHTML=list.length?list.map(dispatchCard).join(''):`<div class="network-empty">${yi('נישטא קיין בקשות אין דעם Filter.','No requests in this filter.')}</div>`}
function dispatchCard(x){const mine=x.claimed_by===userId(),own=x.created_by===userId();return `<article class="dispatch-card" data-dispatch-id="${x.id}"><div class="dispatch-top"><div><h3>${esc(x.title)}</h3><p>${esc(x.details||'')}</p></div><span>${x.due_at?dateText(x.due_at):''}</span></div><div class="dispatch-tags"><span class="${x.status==='open'?'open':x.status==='claimed'?'claimed':x.status==='completed'?'done':''}">${x.status}</span><span class="${x.priority==='urgent'?'urgent':''}">${x.priority}</span><span>${x.category}</span></div><div class="dispatch-owner">${yi('ארויסגעלייגט דורך','Posted by')} ${esc(x.created_name||'Campaign member')}${x.claimed_name?` · ${yi('גענומען דורך','Claimed by')} ${esc(x.claimed_name)}`:''}</div><div class="dispatch-actions">${x.status==='open'?'<button class="claim-btn claim-dispatch">אננעמען</button>':''}${mine&&x.status==='claimed'?'<button class="complete-btn complete-dispatch">פארענדיקט</button><button class="release-btn release-dispatch">צוריקגעבן</button>':''}${(own||mine)&&!['completed','cancelled'].includes(x.status)?'<button class="cancel-btn cancel-dispatch">קענסלען</button>':''}</div></article>`}
function renderRoom(){const tabs=[['all','אלע'],['updates','Updates'],['chizuk','חיזוק'],['guidance','הדרכה'],['ideas','עצות'],['coffee','קאווע שטיבל']];$('#roomTabs').innerHTML=tabs.map(([x,l])=>`<button class="network-tab ${roomChannel===x?'on':''}" data-room-tab="${x}">${l}</button>`).join('');const list=data.messages.filter(x=>roomChannel==='all'||x.channel===roomChannel).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)));$('#roomMessages').innerHTML=list.length?list.map(messageCard).join(''):`<div class="network-empty">${yi('זייט דער ערשטער זיך צו לאזן הערן.','Be the first to speak up.')}</div>`;$('#replyPreview').innerHTML=currentReply?`<div class="room-reply">${yi('ענטפערט אויף א Message','Replying to a message')} <button class="mini-btn" id="clearReply">×</button></div>`:''}
function messageCard(x){const reply=x.reply_to?data.messages.find(m=>m.id===x.reply_to):null,reacted=(x.reacted_by||[]).includes(userId());return `<article class="room-message" data-message-id="${x.id}"><div class="room-message-head"><div class="room-author"><div class="room-avatar">${esc((x.author_name||'?').slice(0,1))}</div><div><strong>${esc(x.author_name)}</strong><small>${dateText(x.created_at)}</small></div></div><span class="room-channel">${esc(x.channel)}</span></div>${reply?`<div class="room-reply"><strong>${esc(reply.author_name)}:</strong> ${esc(reply.body.slice(0,130))}</div>`:''}<div class="room-body">${esc(x.body)}</div><div class="room-actions"><button class="react-room ${reacted?'on':''}">חזק! ${x.reactions||0}</button><button class="reply-room">ענטפערן</button></div></article>`}
function renderAll(){renderGates();renderHome();if(enabled()){renderOffice();renderCommand();renderRoom()}}

async function claimLead(id){const x=data.leads.find(a=>a.id===id);if(!x||x.status!=='available')return toastN('עמיצער האט עס שוין גענומען','Someone already claimed this');x.status='claimed';x.claimed_by=userId();x.claimed_name=userName();x.updated_at=now();saveLocal();await upsertLead(x);renderAll()}
async function releaseLead(id){const x=data.leads.find(a=>a.id===id);if(!x||x.claimed_by!==userId())return;x.status='available';x.claimed_by='';x.claimed_name='';x.updated_at=now();saveLocal();await upsertLead(x);renderAll()}
function saveToKesher(x){const k=`gavhah-kesher-book:${userId()}`,list=JSON.parse(localStorage.getItem(k)||'[]');if(!list.some(a=>a.phone&&x.phone&&a.phone===x.phone))list.unshift({id:uid('contact'),name:x.name,phone:x.phone,phone2:'',email:'',institution:'',role:'donor',subtype:'Campaign lead',labels:['Campaign Office'],status:'active',outlook:'present',importance:x.priority==='urgent'?'critical':'normal',line_number:'',notes:x.note||'',future_mode:x.last_outcome||'',next_action_at:x.next_callback_at||'',expected_amount:x.target||0,last_gift_amount:x.donation_amount||0,last_gift_date:'',privacy:'private',archived:false,created_at:now(),updated_at:now(),call_history:[]});localStorage.setItem(k,JSON.stringify(list));toastN('צוגעלייגט צו אייער פריוואטן קשר־ספר','Added to your private Kesher Book')}
async function claimDispatch(id){const x=data.dispatch.find(a=>a.id===id);if(!x||x.status!=='open')return toastN('עמיצער האט עס שוין אנגענומען','Someone already accepted this');x.status='claimed';x.claimed_by=userId();x.claimed_name=userName();x.updated_at=now();saveLocal();await upsertDispatch(x);renderAll()}
async function dispatchStatus(id,status){const x=data.dispatch.find(a=>a.id===id);if(!x)return;if(status==='open'&&x.claimed_by!==userId())return;if(status==='completed'&&x.claimed_by!==userId())return;if(status==='cancelled'&&x.claimed_by!==userId()&&x.created_by!==userId())return;x.status=status;if(status==='open'){x.claimed_by='';x.claimed_name=''}x.updated_at=now();saveLocal();await upsertDispatch(x);renderAll()}
function categories(){return[['pickup','📦','Pickup / Delivery'],['ride','🚗','Ride / Driver'],['call','☎','Call'],['printing','🖨','Printing'],['event','🎤','Event'],['other','✦','Other']]}
function renderCategories(selected='call'){$('#dispatchCategories').innerHTML=categories().map(([c,i,l])=>`<button type="button" class="dispatch-category ${selected===c?'on':''}" data-category="${c}"><strong>${i} ${l}</strong><small>${yi('קלייבט דעם נאנטסטן סארט','Choose the closest type')}</small></button>`).join('');$('#dispatchCategories').dataset.selected=selected}

function bind(){
 $('#officeSearch').addEventListener('input',renderOffice);$('#commandSearch').addEventListener('input',renderCommand);$('#addLead').onclick=()=>$('#leadEditor').classList.add('on');$('#addDispatch').onclick=()=>{renderCategories();$('#dispatchEditor').classList.add('on')};
 $('#officeTabs').addEventListener('click',e=>{const b=e.target.closest('[data-office-tab]');if(b){officeTab=b.dataset.officeTab;renderOffice()}});$('#commandTabs').addEventListener('click',e=>{const b=e.target.closest('[data-command-tab]');if(b){commandTab=b.dataset.commandTab;renderCommand()}});$('#roomTabs').addEventListener('click',e=>{const b=e.target.closest('[data-room-tab]');if(b){roomChannel=b.dataset.roomTab;renderRoom()}});
 $('#officeList').addEventListener('click',e=>{const card=e.target.closest('[data-lead-id]');if(!card)return;const x=data.leads.find(a=>a.id===card.dataset.leadId);if(e.target.closest('.claim-lead'))claimLead(x.id);if(e.target.closest('.release-lead'))releaseLead(x.id);if(e.target.closest('.save-personal-kesher'))saveToKesher(x);if(e.target.closest('.log-lead')){currentLead=x.id;$('#leadOutcomeStatus').value='contacted';$('#leadOutcomeNote').value='';$('#leadDonation').value='';$('#leadCallback').value=x.next_callback_at?x.next_callback_at.slice(0,16):'';$('#leadOutcome').classList.add('on')}});
 $('#dispatchList').addEventListener('click',e=>{const card=e.target.closest('[data-dispatch-id]');if(!card)return;const id=card.dataset.dispatchId;if(e.target.closest('.claim-dispatch'))claimDispatch(id);if(e.target.closest('.release-dispatch'))dispatchStatus(id,'open');if(e.target.closest('.complete-dispatch'))dispatchStatus(id,'completed');if(e.target.closest('.cancel-dispatch'))dispatchStatus(id,'cancelled')});
 $('#dispatchCategories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;renderCategories(b.dataset.category)});
 $('#saveLead').onclick=async()=>{const name=$('#leadName').value.trim();if(!name)return toastN('לייגט אריין א נאמען אדער Label','Enter a name or label');const x={id:crypto.randomUUID?crypto.randomUUID():uid('lead'),name,phone:$('#leadPhone').value.trim(),source:$('#leadSource').value.trim(),target:Number($('#leadTarget').value||0),priority:$('#leadPriority').value,status:'available',claimed_by:'',claimed_name:'',call_count:0,last_outcome:'',donation_amount:0,next_callback_at:'',note:$('#leadNote').value.trim(),created_at:now(),updated_at:now()};data.leads.unshift(x);saveLocal();await upsertLead(x);close();renderAll()};
 $('#saveLeadOutcome').onclick=async()=>{const x=data.leads.find(a=>a.id===currentLead);if(!x)return;const outcome=$('#leadOutcomeStatus').value;x.call_count=Number(x.call_count||0)+1;x.status=outcome;x.last_outcome=$('#leadOutcomeNote').value.trim()||outcome;x.donation_amount=Number($('#leadDonation').value||0);x.next_callback_at=$('#leadCallback').value||'';x.updated_at=now();saveLocal();await upsertLead(x);close();renderAll()};
 $('#saveDispatch').onclick=async()=>{const title=$('#dispatchTitle').value.trim();if(!title)return toastN('שרייבט וואס דארף געטון ווערן','Describe what needs to be done');const x={id:crypto.randomUUID?crypto.randomUUID():uid('job'),title,details:$('#dispatchDetails').value.trim(),category:$('#dispatchCategories').dataset.selected||'other',priority:$('#dispatchPriority').value,status:'open',created_by:userId(),created_name:userName(),claimed_by:'',claimed_name:'',due_at:$('#dispatchDue').value||'',created_at:now(),updated_at:now()};data.dispatch.unshift(x);saveLocal();await upsertDispatch(x);close();renderAll()};
 $('#sendRoom').onclick=async()=>{const body=$('#roomText').value.trim();if(!body)return;const x={id:crypto.randomUUID?crypto.randomUUID():uid('msg'),author_id:userId(),author_name:userName(),channel:$('#roomComposeChannel').value,body,reply_to:currentReply,created_at:now(),reactions:0,reacted_by:[]};data.messages.unshift(x);saveLocal();await insertMessage(x);$('#roomText').value='';currentReply='';renderRoom();renderHome()};
 $('#roomMessages').addEventListener('click',e=>{const card=e.target.closest('[data-message-id]');if(!card)return;const x=data.messages.find(a=>a.id===card.dataset.messageId);if(e.target.closest('.reply-room')){currentReply=x.id;renderRoom();$('#roomText').focus()}if(e.target.closest('.react-room')){x.reacted_by=x.reacted_by||[];const i=x.reacted_by.indexOf(userId());if(i>=0){x.reacted_by.splice(i,1);x.reactions=Math.max(0,Number(x.reactions||0)-1)}else{x.reacted_by.push(userId());x.reactions=Number(x.reactions||0)+1}saveLocal();renderRoom()}});
 $('#replyPreview').addEventListener('click',e=>{if(e.target.closest('#clearReply')){currentReply='';renderRoom()}});
 $$('[data-network-close]').forEach(b=>b.onclick=close);$$('#leadEditor,#leadOutcome,#dispatchEditor').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)close()}));
}
function close(){$$('#leadEditor,#leadOutcome,#dispatchEditor').forEach(m=>m.classList.remove('on'))}
function patch(){if(typeof renderAll==='function'&&!window.__networkPatched){const old=renderAll;renderAll=function(){old();renderAll()};window.__networkPatched=true}}
async function initData(){const k=key();if(k===loadedKey)return;loadedKey=k;if(channel&&typeof afClient!=='undefined'){try{await afClient.removeChannel(channel)}catch{}channel=null}loadLocal();renderAll();await loadCloud();renderAll()}
function init(){inject();patch();renderAll();setInterval(()=>{if(userId()&&key()!==loadedKey)initData()},500);initData()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
