/* GAVHAH Focus Ladder preview */
(function(){
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const tr=(a,b)=>(typeof language!=='undefined'&&language==='en'?b:a);
const esc=(v='')=>{const d=document.createElement('div');d.textContent=String(v);return d.innerHTML};
const plans=['Personal Askan','Chesed Quick','Askan Pro','Gabbai Pro','Organization','Custom'];
const meta={
'Personal Askan':{c:'free',t:['מיין פאוקעס','My Focus'],s:'Personal Focus Center',q:['וואס איז דער איין זאך וואס דארף יעצט באקומען מיין קאפ?','What deserves my attention now?']},
'Chesed Quick':{c:'quick',t:['היינט אינעם קאמפיין','Today in the Campaign'],s:'Campaign Focus Board',q:['וואס מוז דער גאנצער קאמפיין היינט באוועגן?','What must the whole campaign move today?']},
'Askan Pro':{c:'pro',t:['דער נעקסטער בעסטער שריט','The Next Best Move'],s:'Campaign Navigator',q:['וואס ברענגט דעם גרעסטן פארשריט די קומענדיגע זיבן טעג?','What creates the greatest progress in seven days?']},
'Gabbai Pro':{c:'gabbai',t:['וואס שטעקט צווישן די טימס?','What Is Stuck Between Teams?'],s:'Operations Compass',q:['וואו דארף אחריות אדער אפעראציע ווערן אויסגעקלארט?','Where do ownership or operations need clarity?']},
'Organization':{c:'organization',t:['וואו זאל הנהלה לייגן כוחות?','Where Should Leadership Put Resources?'],s:'Leadership Focus Network',q:['וועלכער קאמפיין אדער באשלוס דארף יעצט הנהלה?','Which campaign or decision needs leadership now?']},
'Custom':{c:'custom',t:['אייער Mission System','Your Mission System'],s:'Mission Intelligence Layer',q:['וועלכע אייגענע דאטע און Workflows דארפן פירן די אפעראציע?','Which custom data and workflows should guide the operation?']}
};
const preview=new URLSearchParams(location.search).get('focusPreview')==='1';
const realPlan=()=>typeof state!=='undefined'&&state?.campaign?.plan?state.campaign.plan:'Personal Askan';
const user=()=>typeof afCurrentUser!=='undefined'&&afCurrentUser?.id?afCurrentUser.id:'preview';
const campaign=()=>typeof state!=='undefined'&&state?.campaign?.id?state.campaign.id:'campaign';
let plan=preview?'Chesed Quick':realPlan(),data={};
const key=()=>`gavhah-focus-ladder:${user()}:${campaign()}:${plan}`;
function defaults(){return{outcome:'',blocker:'',steps:[{t:'',o:'',s:'open'},{t:'',o:'',s:'open'},{t:'',o:'',s:'open'}],review:'',sprint:'',next:'',decision:'',custom:'',saved:''}}
function load(){try{data={...defaults(),...JSON.parse(localStorage.getItem(key())||'{}')}}catch{data=defaults()}}
function save(){collect();data.saved=new Date().toISOString();localStorage.setItem(key(),JSON.stringify(data));note();if(typeof toast==='function')toast('דער Focus System איז געהיטן','Focus system saved')}
function inject(){if($('#focusLadder'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='focus-ladder.css?v=1';document.head.appendChild(l);$('#focus')?.insertAdjacentHTML('beforeend',`<div id="focusLadder" class="focus-ladder-shell"><div id="focusPreviewBar" class="focus-preview-bar" style="display:${preview?'block':'none'}"><strong>${tr('Preview: זעט וויאזוי דער Focus System וואקסט מיט יעדן פלאן','Preview how the focus system grows with each plan')}</strong><small>${tr('דאס טוישט נישט דעם אמת׳ן אקאונט־פלאן.','This does not change the real account plan.')}</small><div id="focusRankTabs" class="focus-rank-tabs"></div></div><div id="focusLadderContent"></div></div>`)}
function tabs(){if(!preview)return;$('#focusRankTabs').innerHTML=plans.map(p=>`<button class="focus-rank-tab ${p===plan?'on':''}" data-plan="${p}">${p==='Personal Askan'?'Free':p}</button>`).join('')}
function head(){const m=meta[plan];if(plan==='Personal Askan')return`<div class="focus-free-unchanged"><strong>${tr('דער Free Plan בלייבט פונקט אזוי','The free plan stays exactly as it is')}</strong><small>${tr('איין הויפט פאוקעס, דריי Priorities, Brain Dump, Blocker און Next Step. פשוט, שיין און פריוואט.','One main focus, three priorities, brain dump, blocker and next step. Simple, beautiful and private.')}</small></div>`;return`<div class="focus-tier-head ${m.c}"><div class="focus-tier-kicker">${plan} · ${m.s}</div><h2>${tr(...m.t)}</h2><p>${tr(...m.q)}</p><div class="focus-tier-question">${tr('יעדער העכערער פלאן האלט אלעס פון אונטן און לייגט צו א נייע מדריגה פון קלארקייט.','Every higher plan keeps the lower layers and adds a stronger level of clarity.')}</div></div>`}
function quick(){return`<div class="focus-panel"><h3>1. ${tr('דער Shared Outcome פאר היינט','Today’s Shared Outcome')}</h3><p class="focus-sub">${tr('יעדער עסקן זאל וויסן וואס דער קאמפיין מוז היינט באוועגן.','Every member should know what the campaign must move today.')}</p><input id="flOutcome" class="focus-outcome-input" value="${esc(data.outcome)}" placeholder="למשל: פארמאכן 8 Follow-ups און $12,000 Pledges"></div><div class="focus-panel"><h3>2. ${tr('די דריי Team Moves','The Three Team Moves')}</h3><div class="focus-three-list">${data.steps.slice(0,3).map((x,i)=>`<div class="focus-shared-step" data-step="${i}"><div class="focus-step-num">${i+1}</div><div class="focus-step-fields"><input data-f="t" value="${esc(x.t)}" placeholder="וואס דארף געטון ווערן?"><div class="focus-inline-grid"><input data-f="o" value="${esc(x.o)}" placeholder="Owner"><select data-f="s"><option ${x.s==='open'?'selected':''} value="open">Open</option><option ${x.s==='active'?'selected':''} value="active">Active</option><option ${x.s==='blocked'?'selected':''} value="blocked">Blocked</option><option ${x.s==='done'?'selected':''} value="done">Done</option></select></div></div></div>`).join('')}</div></div><div class="focus-panel"><h3>3. ${tr('דער הויפט Blocker','The Main Blocker')}</h3><textarea id="flBlocker" placeholder="וואס האלט צוריק דעם Shared Outcome?">${esc(data.blocker)}</textarea></div><div class="focus-panel"><h3>4. End-of-Day Review</h3><textarea id="flReview" placeholder="וואס איז געלונגען, און וואס טוישן מארגן?">${esc(data.review)}</textarea></div>`}
function pro(){return`<div class="focus-panel"><h3>5. 7-Day Campaign Sprint</h3><input id="flSprint" value="${esc(data.sprint)}" placeholder="דער מעסטבארער רעזולטאט פאר די קומענדיגע 7 טעג"><div class="focus-radar" style="margin-top:10px"><div class="focus-radar-card"><span>Overdue</span><strong>6</strong><small>Tasks & promises</small></div><div class="focus-radar-card"><span>Follow-ups</span><strong>14</strong><small>People waiting</small></div><div class="focus-radar-card"><span>Quiet Members</span><strong>3</strong><small>No recent action</small></div><div class="focus-radar-card"><span>At Risk</span><strong>2</strong><small>Goals under pressure</small></div></div></div><div class="focus-panel"><h3>6. Next Best Action</h3><div class="focus-action-card"><strong>${tr('דאטע ווערט א קלארער נעקסטער שריט','Data becomes a clear next move')}</strong><textarea id="flNext" placeholder="למשל: געבן די 5 הייססטע Callbacks פאר ר׳ יואל">${esc(data.next)}</textarea></div></div>`}
function gabbai(){return`<div class="focus-panel"><h3>7. Operations Lanes</h3><div class="focus-lane-grid"><div class="focus-lane"><div class="focus-lane-head"><strong>Calls & Donors</strong><span class="focus-lane-status">Active</span></div><p>5 high-value callbacks waiting.</p></div><div class="focus-lane"><div class="focus-lane-head"><strong>Event & Logistics</strong><span class="focus-lane-status wait">Waiting</span></div><p>Driver confirmation is still open.</p></div><div class="focus-lane"><div class="focus-lane-head"><strong>Finance & Checks</strong><span class="focus-lane-status risk">Risk</span></div><p>3 checks need reconciliation.</p></div><div class="focus-lane"><div class="focus-lane-head"><strong>Printing & Content</strong><span class="focus-lane-status">Active</span></div><p>Literature is ready for pickup.</p></div></div></div><div class="focus-panel"><h3>8. Handoffs & Waiting-On</h3><div class="focus-handoff"><div><strong>Donor callback list</strong><small>ר׳ יואל → ר׳ מנחם</small></div><span>Tonight</span></div><div class="focus-handoff"><div><strong>Printing pickup</strong><small>Office → Open</small></div><span>Before 6</span></div></div>`}
function organization(){return`<div class="focus-panel"><h3>9. Portfolio Focus Map</h3><div class="focus-portfolio-grid"><div class="focus-portfolio-card"><div class="focus-portfolio-top"><h4>משפחה הילף</h4><strong>68%</strong></div><p>Team A · Follow-ups slowing</p><div class="focus-progress"><i style="width:68%"></i></div></div><div class="focus-portfolio-card"><div class="focus-portfolio-top"><h4>מסיבה קאמפיין</h4><strong>42%</strong></div><p>Events · Speaker unconfirmed</p><div class="focus-progress"><i style="width:42%"></i></div></div><div class="focus-portfolio-card"><div class="focus-portfolio-top"><h4>Emergency Fund</h4><strong>81%</strong></div><p>Finance · No major blocker</p><div class="focus-progress"><i style="width:81%"></i></div></div></div></div><div class="focus-panel"><h3>10. Leadership Decision Queue</h3><textarea id="flDecision" placeholder="וועלכער באשלוס דארף הנהלה יעצט פארמאכן?">${esc(data.decision)}</textarea></div>`}
function custom(){return`<div class="focus-panel"><h3>11. Custom Mission Intelligence</h3><p class="focus-sub">Hotline, API, אייגענע Playbooks, Custom Signals און Managed Alerts.</p><textarea id="flCustom" placeholder="וועלכער אייגענער Signal אדער Automation דארף דער מוסד?">${esc(data.custom)}</textarea></div>`}
function render(){tabs();const rank=plans.indexOf(plan);let h=head();if(rank>=1)h+=quick();if(rank>=2)h+=pro();if(rank>=3)h+=gabbai();if(rank>=4)h+=organization();if(rank>=5)h+=custom();if(rank>=1)h+=`<div class="focus-save-row"><button id="flSave" class="btn">${tr('היטן Focus System','Save Focus System')}</button><button id="flReset" class="soft">${tr('אנהייבן פריש','Start fresh')}</button></div><div id="flNote" class="focus-save-note"></div>`;$('#focusLadderContent').innerHTML=h;$('#flSave')?.addEventListener('click',save);$('#flReset')?.addEventListener('click',()=>{localStorage.removeItem(key());load();render()});note()}
function collect(){if(plans.indexOf(plan)<1)return;data.outcome=$('#flOutcome')?.value.trim()||'';data.blocker=$('#flBlocker')?.value.trim()||'';data.review=$('#flReview')?.value.trim()||'';data.sprint=$('#flSprint')?.value.trim()||data.sprint;data.next=$('#flNext')?.value.trim()||data.next;data.decision=$('#flDecision')?.value.trim()||data.decision;data.custom=$('#flCustom')?.value.trim()||data.custom;data.steps=$$('.focus-shared-step').map(r=>({t:r.querySelector('[data-f="t"]')?.value.trim()||'',o:r.querySelector('[data-f="o"]')?.value.trim()||'',s:r.querySelector('[data-f="s"]')?.value||'open'}))}
function note(){const n=$('#flNote');if(n)n.textContent=data.saved?`${tr('לעצט געהיטן','Last saved')}: ${new Date(data.saved).toLocaleString()}`:tr('Preview Save ווערט געהיטן אויפן Device.','Preview save is stored on this device.')}
function bind(){$('#focusRankTabs')?.addEventListener('click',e=>{const b=e.target.closest('[data-plan]');if(!b)return;collect();plan=b.dataset.plan;load();render()})}
function watch(){if(preview)return;const p=realPlan();if(p!==plan){plan=p;load();render()}}
function init(){inject();load();render();bind();setInterval(watch,800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
